### ISSUE TITLE
Jar运行成功，但无法挂载

### ISSUE THREAD

**Issue by voodka** [VGEAREN/pikpak-webdav#2]
**描述：**
请问，Jar运行之后，是通过本机地址的8080端口挂载吗，用户名密码是什么？pikpak的用户名密码吗，感觉挂载不成功有可能是我的用户名是邮箱账号，里面有个@字符

**复现：**
![image](https://user-images.githubusercontent.com/13945856/153337940-dde692c9-a7d2-42cb-9ef2-a9058db02037.png)

**预期：**
RaiDrive挂载不上，401错误似乎是指授权失败 

**截图：**
![image](https://user-images.githubusercontent.com/13945856/153337696-78428f37-35f4-46e1-b545-358411d3731a.png)

**环境：**
 - Jar
 - latest

**运行参数：**
最好能把运行参数贴出来

**Comment by VGEAREN** [comment]
@voodka 默认认证账号密码admin/admin，需要修改添加参数 -e PIKPAK_AUTH_USER_NAME="USERNAME" -e PIKPAK_AUTH_PASSWORD="PASSWORD"
