### ISSUE TITLE
无法在window上挂载webdav

### ISSUE THREAD

**Issue by jtyoui** [VGEAREN/pikpak-webdav#4]
**描述：**
无法在window上挂载wendav。一直在不停的提示叫我输入密码。

**复现：**
一直在重复提示密码，但是网页上是可以的。不可能是密码错误。

**截图：**
![image](https://user-images.githubusercontent.com/28988355/169644783-e7d2f2f9-1fc2-423b-b9cf-f7a76caa9dc0.png)
![image](https://user-images.githubusercontent.com/28988355/169644789-2cfb0eef-5b49-4327-b6ca-926f0fd52d2a.png)

**环境：**
 - Docker

**Comment by VGEAREN** [comment]
有没有可能是你挂载方式不对
